--
-- Copyright 2026 Datastrato Inc..
--

-- Enterprise extension JDBC schema.

CREATE TABLE IF NOT EXISTS scim_token_meta (
    token_id BIGINT NOT NULL,
    token_name VARCHAR(256) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at BIGINT NOT NULL DEFAULT 0,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    last_used_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (token_id),
    UNIQUE (token_name, deleted_at),
    UNIQUE (token_hash, deleted_at)
);
COMMENT ON TABLE scim_token_meta IS 'scim token metadata';

CREATE TABLE IF NOT EXISTS scim_user_meta (
    user_id BIGINT NOT NULL,
    user_name VARCHAR(128) NOT NULL,
    external_id VARCHAR(256),
    enabled SMALLINT NOT NULL DEFAULT 1,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id),
    UNIQUE (user_name, deleted_at),
    UNIQUE (external_id, deleted_at)
);
COMMENT ON TABLE scim_user_meta IS 'scim user metadata';

CREATE TABLE IF NOT EXISTS scim_group_meta (
    group_id BIGINT NOT NULL,
    group_name VARCHAR(128) NOT NULL,
    group_comment VARCHAR(1024) DEFAULT '',
    external_id VARCHAR(256),
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (group_id),
    UNIQUE (group_name, deleted_at),
    UNIQUE (external_id, deleted_at)
);
COMMENT ON TABLE scim_group_meta IS 'scim group metadata';

CREATE TABLE IF NOT EXISTS scim_user_group_rel (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (user_id, group_id, deleted_at)
);
CREATE INDEX IF NOT EXISTS scim_user_group_rel_idx_user_id ON scim_user_group_rel (user_id);
CREATE INDEX IF NOT EXISTS scim_user_group_rel_idx_group_id ON scim_user_group_rel (group_id);
COMMENT ON TABLE scim_user_group_rel IS 'scim user group relation';

CREATE TABLE IF NOT EXISTS scim_error_history (
    error_id BIGINT NOT NULL,
    http_method VARCHAR(16) NOT NULL,
    request_path VARCHAR(1024) NOT NULL,
    http_status INT NOT NULL,
    scim_type VARCHAR(64) DEFAULT NULL,
    error_detail VARCHAR(1024) NOT NULL DEFAULT '',
    principal VARCHAR(256) NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL,
    PRIMARY KEY (error_id)
);
CREATE INDEX IF NOT EXISTS scim_error_history_idx_created ON scim_error_history (created_at);
COMMENT ON TABLE scim_error_history IS 'scim protocol error history';

CREATE TABLE IF NOT EXISTS catalog_connection_test_meta (
    catalog_id BIGINT NOT NULL,
    type VARCHAR(256) NOT NULL,
    catalog_version INT NOT NULL,
    test_status VARCHAR(16) NOT NULL,
    last_tested_at BIGINT NOT NULL,
    error_message VARCHAR(4096) DEFAULT NULL,
    PRIMARY KEY (catalog_id, type)
);

COMMENT ON TABLE catalog_connection_test_meta IS 'catalog connection test results';
COMMENT ON COLUMN catalog_connection_test_meta.catalog_id IS 'catalog id';
COMMENT ON COLUMN catalog_connection_test_meta.type IS 'Catalog or credential connection test type';
COMMENT ON COLUMN catalog_connection_test_meta.catalog_version IS 'tested catalog version';
COMMENT ON COLUMN catalog_connection_test_meta.test_status IS 'completed connection test status';
COMMENT ON COLUMN catalog_connection_test_meta.last_tested_at IS 'test completion time in ms';
COMMENT ON COLUMN catalog_connection_test_meta.error_message IS 'safe connection failure message';
