--
-- Copyright 2026 Datastrato Pvt Ltd.
-- This software is licensed under the Apache License version 2.
--

-- Enterprise extension JDBC schema.

CREATE TABLE IF NOT EXISTS scim_token_meta (
    token_id BIGINT NOT NULL,
    metalake_id BIGINT NOT NULL,
    token_name VARCHAR(256) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at BIGINT NOT NULL DEFAULT 0,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    last_used_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (token_id),
    UNIQUE (metalake_id, token_name, deleted_at),
    UNIQUE (token_hash, deleted_at)
);
COMMENT ON TABLE scim_token_meta IS 'scim token metadata';

COMMENT ON COLUMN scim_token_meta.token_id IS 'token id';
COMMENT ON COLUMN scim_token_meta.metalake_id IS 'metalake id';
COMMENT ON COLUMN scim_token_meta.token_name IS 'scim token name';
COMMENT ON COLUMN scim_token_meta.token_hash IS 'SHA-256 hex digest of scim token value';
COMMENT ON COLUMN scim_token_meta.expires_at IS 'token expiry time in ms, 0 means never expires';
COMMENT ON COLUMN scim_token_meta.audit_info IS 'scim token audit info';
COMMENT ON COLUMN scim_token_meta.deleted_at IS 'scim token deleted at';
COMMENT ON COLUMN scim_token_meta.updated_at IS 'updated at';
COMMENT ON COLUMN scim_token_meta.last_used_at IS 'last authenticated SCIM request time in ms, 0 means never';

CREATE TABLE IF NOT EXISTS scim_user_group_rel (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    audit_info TEXT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (metalake_id, user_id, group_id, deleted_at)
);

CREATE INDEX IF NOT EXISTS scim_user_group_rel_idx_metalake_id ON scim_user_group_rel (metalake_id);
CREATE INDEX IF NOT EXISTS scim_user_group_rel_idx_user_id ON scim_user_group_rel (user_id);
CREATE INDEX IF NOT EXISTS scim_user_group_rel_idx_group_id ON scim_user_group_rel (group_id);
COMMENT ON TABLE scim_user_group_rel IS 'scim user group relation';

COMMENT ON COLUMN scim_user_group_rel.id IS 'auto increment id';
COMMENT ON COLUMN scim_user_group_rel.metalake_id IS 'metalake id';
COMMENT ON COLUMN scim_user_group_rel.user_id IS 'user id';
COMMENT ON COLUMN scim_user_group_rel.group_id IS 'group id';
COMMENT ON COLUMN scim_user_group_rel.audit_info IS 'relation audit info';
COMMENT ON COLUMN scim_user_group_rel.current_version IS 'relation current version';
COMMENT ON COLUMN scim_user_group_rel.last_version IS 'relation last version';
COMMENT ON COLUMN scim_user_group_rel.deleted_at IS 'relation deleted at';
