#
# Copyright 2026 Datastrato Inc.
#
# jdbc-url = jdbc:odps:http://service.cn-hangzhou.maxcompute.aliyun.com/api?project=your_project
# jdbc-user = your_access_key_id
# jdbc-password = your_access_key_secret
# jdbc-driver = com.aliyun.odps.jdbc.OdpsDriver
