/*
 * Copyright 2024 Datastrato Pvt Ltd.
 * This software is licensed under the Apache License version 2.
 */
package com.datastrato.gravitino.metrics.storage.relational.service;

import com.datastrato.gravitino.metrics.MetricsCollector;
import com.datastrato.gravitino.metrics.dto.MetricDTO;
import com.datastrato.gravitino.metrics.storage.relational.MetricDirtyPO;
import com.datastrato.gravitino.metrics.storage.relational.MetricPO;
import com.datastrato.gravitino.metrics.storage.relational.OwnerNameRelPO;
import com.datastrato.gravitino.metrics.storage.relational.TagNameMetadataObjectRelPO;
import com.datastrato.gravitino.metrics.storage.relational.mapper.MetricDataMapper;
import com.datastrato.gravitino.metrics.storage.relational.utils.DatastratoPOConverters;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.annotation.Nullable;
import org.apache.gravitino.Entity;
import org.apache.gravitino.NameIdentifier;
import org.apache.gravitino.exceptions.NoSuchEntityException;
import org.apache.gravitino.exceptions.NoSuchMetalakeException;
import org.apache.gravitino.exceptions.NoSuchUserException;
import org.apache.gravitino.meta.UserEntity;
import org.apache.gravitino.server.authorization.MetadataAuthzHelper;
import org.apache.gravitino.server.authorization.expression.AuthorizationExpressionConstants;
import org.apache.gravitino.storage.relational.po.SecurableObjectPO;
import org.apache.gravitino.storage.relational.po.UserRoleRelPO;
import org.apache.gravitino.storage.relational.service.MetalakeMetaService;
import org.apache.gravitino.storage.relational.service.UserMetaService;
import org.apache.gravitino.storage.relational.utils.SessionUtils;
import org.apache.gravitino.utils.NameIdentifierUtil;

public class MetricDataService {
  private static final int INSERT_BATCH_SIZE = 1_000;
  private static final MetricDataService INSTANCE = new MetricDataService();

  private boolean enableAuthorization;

  @SuppressWarnings("unused")
  private MetricsCollector metricsCollector;

  private MetricDataService() {}

  public static MetricDataService getInstance() {
    return INSTANCE;
  }

  public void initialize(boolean enableAuthorization) {
    this.enableAuthorization = enableAuthorization;
    this.metricsCollector = MetricsCollector.getInstance();
  }

  // For testing only
  void setMetricsCollector(MetricsCollector metricsCollector) {
    this.metricsCollector = metricsCollector;
  }

  /** Supported dashboard metric names. */
  public enum Metric {
    /** Number of visible TABLE, VIEW, TOPIC, FILESET, and MODEL assets. */
    ASSET_COUNT("asset_count"),

    /** Number of visible assets with a direct or inherited tag. */
    TAGGED_ASSET_COUNT("tagged_asset_count"),

    /** Number of visible assets with a direct owner. */
    OWNED_ASSET_COUNT("owned_asset_count"),

    /** Number of visible assets with a direct or inherited enabled policy. */
    POLICY_COVERED_ASSET_COUNT("policy_covered_asset_count"),

    /** Number of current, non-deleted policies in the metalake. */
    POLICY_COUNT("policy_count"),

    /** Number of current, non-deleted policies whose current version is disabled. */
    DISABLED_POLICY_COUNT("disabled_policy_count");

    private final String name;

    Metric(String name) {
      this.name = name;
    }

    public String getName() {
      return name;
    }

    public static Metric fromName(String name) {
      for (Metric metric : values()) {
        if (metric.name.equalsIgnoreCase(name)) {
          return metric;
        }
      }
      throw new IllegalArgumentException("Unknown metric name: " + name);
    }
  }

  public MetricDTO[] getMetricsByNameAndTimestamp(
      String metalakeName,
      String userName,
      String[] metricNames,
      long startTimestamp,
      long endTimestamp) {
    // this method is used by GravitinoMetricsService to query metrics, so we can not use
    // metalakeSnapshot, because it's generated by GravitinoMetricsService
    long metalakeId;
    try {
      metalakeId = MetalakeMetaService.getInstance().getMetalakeIdByName(metalakeName);
    } catch (NoSuchEntityException e) {
      throw new NoSuchMetalakeException(e, "Metalake not found: %s", metalakeName);
    }

    long userId = MetricsCollector.MOCK_USER_ID_FOR_DISABLE_AUTHZ;
    if (enableAuthorization) {
      try {
        UserEntity userEntity =
            UserMetaService.getInstance()
                .getUserByIdentifier(NameIdentifierUtil.ofUser(metalakeName, userName));
        userId = userEntity.id();
      } catch (NoSuchEntityException e) {
        throw new NoSuchUserException(
            e, "User not found: %s for metalake: %s", userName, metalakeName);
      }
      NameIdentifier[] authResult =
          MetadataAuthzHelper.filterByExpression(
              metalakeName,
              AuthorizationExpressionConstants.METALAKE_OWNER_AUTHORIZATION_EXPRESSION,
              Entity.EntityType.METALAKE,
              new NameIdentifier[] {NameIdentifierUtil.ofMetalake(metalakeName)});
      userId = authResult.length == 0 ? userId : MetricsCollector.MOCK_USER_ID_FOR_METALAKE_OWNER;
    }

    long finalUserId = userId;
    List<MetricPO> metricPOs =
        SessionUtils.getWithoutCommit(
            MetricDataMapper.class,
            mapper -> {
              Timestamp start = new Timestamp(startTimestamp);
              Timestamp end = new Timestamp(endTimestamp);
              List<MetricPO> history =
                  mapper.getMetricPOsByUserIdMetricNamesAndTimestamp(
                      metalakeId, finalUserId, metricNames, start, end);
              List<MetricPO> current =
                  mapper.getCurrentMetricPOsByUserIdMetricNamesAndTimestamp(
                      metalakeId, finalUserId, metricNames, start, end);
              return mergeMetrics(history, current);
            });
    return DatastratoPOConverters.fromMetricPOs(metricPOs);
  }

  public long getTagCountByMetalakeId(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.getTagCountByMetalakeId(metalakeId));
  }

  public void insertMetrics(long metalakeId, long userId, List<MetricPO> metrics) {
    if (metrics.isEmpty()) {
      return;
    }
    SessionUtils.doWithCommit(
        MetricDataMapper.class, mapper -> mapper.insertMetricsData(metalakeId, userId, metrics));
  }

  /**
   * Atomically replaces every current metric for one metalake.
   *
   * @param metalakeId the metalake ID
   * @param metricsByUser metrics grouped by persisted user ID
   * @param updatedTime the shared current snapshot timestamp
   */
  public void replaceCurrentMetrics(
      long metalakeId, Map<Long, List<MetricPO>> metricsByUser, long updatedTime) {
    replaceMetrics(metalakeId, metricsByUser, updatedTime, false, null);
  }

  /**
   * Atomically replaces current metrics and marks the metalake dirty for a follow-up retry.
   *
   * @param metalakeId the metalake ID
   * @param metricsByUser metrics grouped by persisted user ID
   * @param updatedTime the shared current snapshot timestamp
   * @param dirtyEventTime timestamp used to create or advance the dirty marker
   */
  public void replaceCurrentMetricsAndMarkDirty(
      long metalakeId,
      Map<Long, List<MetricPO>> metricsByUser,
      long updatedTime,
      long dirtyEventTime) {
    replaceMetrics(metalakeId, metricsByUser, updatedTime, false, dirtyEventTime);
  }

  /**
   * Atomically replaces current metrics and appends the corresponding history snapshot.
   *
   * @param metalakeId the metalake ID
   * @param metricsByUser metrics grouped by persisted user ID
   * @param runTime the shared timestamp for both current and history rows
   */
  public void replaceCurrentAndAppendHistory(
      long metalakeId, Map<Long, List<MetricPO>> metricsByUser, long runTime) {
    replaceMetrics(metalakeId, metricsByUser, runTime, true, null);
  }

  /**
   * Atomically replaces current metrics, appends history, and marks the metalake dirty.
   *
   * @param metalakeId the metalake ID
   * @param metricsByUser metrics grouped by persisted user ID
   * @param runTime the shared timestamp for current and history rows
   * @param dirtyEventTime timestamp used to create or advance the dirty marker
   */
  public void replaceCurrentAndAppendHistoryAndMarkDirty(
      long metalakeId, Map<Long, List<MetricPO>> metricsByUser, long runTime, long dirtyEventTime) {
    replaceMetrics(metalakeId, metricsByUser, runTime, true, dirtyEventTime);
  }

  /**
   * Marks a metalake dirty and resets any pending retry state.
   *
   * @param metalakeId the metalake ID
   * @param eventTime the event timestamp in milliseconds
   */
  public void markMetalakeDirty(long metalakeId, long eventTime) {
    SessionUtils.doWithCommit(
        MetricDataMapper.class,
        mapper -> mapper.markMetalakeDirty(metalakeId, new Timestamp(eventTime)));
  }

  /**
   * Returns dirty metalakes that are ready for recomputation.
   *
   * @param quietCutoff events at or before this time have passed the quiet period
   * @param maxDebounceCutoff bursts starting at or before this time reached maximum debounce
   * @param now the current timestamp in milliseconds
   * @return due dirty markers ordered by their first event time
   */
  public List<MetricDirtyPO> listDueDirtyMetalakes(
      long quietCutoff, long maxDebounceCutoff, long now) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class,
        mapper ->
            mapper.listDueDirtyMetalakes(
                new Timestamp(quietCutoff), new Timestamp(maxDebounceCutoff), new Timestamp(now)));
  }

  /**
   * Returns the latest dirty state for a metalake.
   *
   * @param metalakeId the metalake ID
   * @return the dirty marker, or {@code null} when the metalake is clean
   */
  @Nullable
  public MetricDirtyPO getDirtyMetalake(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.getDirtyMetalake(metalakeId));
  }

  /**
   * Deletes a dirty marker only when no newer event changed its revision.
   *
   * @param metalakeId the metalake ID
   * @param revision the expected dirty revision
   * @return whether the expected marker was deleted
   */
  public boolean deleteDirtyIfRevision(long metalakeId, long revision) {
    return SessionUtils.doWithCommitAndFetchResult(
            MetricDataMapper.class, mapper -> mapper.deleteDirtyIfRevision(metalakeId, revision))
        > 0;
  }

  /**
   * Records retry state only when no newer event changed the dirty revision.
   *
   * @param metalakeId the metalake ID
   * @param revision the expected dirty revision
   * @param retryCount the consecutive failure count
   * @param retryAfter the earliest retry time in milliseconds
   * @param lastError the truncated failure message
   * @return whether retry state was stored for the expected revision
   */
  public boolean markRetryIfRevision(
      long metalakeId, long revision, int retryCount, long retryAfter, String lastError) {
    return SessionUtils.doWithCommitAndFetchResult(
            MetricDataMapper.class,
            mapper ->
                mapper.markRetryIfRevision(
                    metalakeId, revision, retryCount, new Timestamp(retryAfter), lastError))
        > 0;
  }

  public void cleanMetricsByTimestamp(long oldestTimestamp) {
    SessionUtils.doWithCommit(
        MetricDataMapper.class,
        mapper -> mapper.cleanMetricsByTimestamp(new Timestamp(oldestTimestamp)));
  }

  public void cleanInvalidMetrics() {
    SessionUtils.doWithCommit(
        MetricDataMapper.class,
        mapper -> {
          mapper.cleanInvalidMetrics();
          mapper.cleanInvalidCurrentMetrics();
          mapper.cleanInvalidDirtyMetrics();
        });
  }

  public List<UserRoleRelPO> listUserRoleRelsByUserIds(Set<Long> userIds) {
    if (userIds.isEmpty()) {
      return Collections.emptyList();
    }
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listUserRoleRelsByUserIds(userIds));
  }

  public List<OwnerNameRelPO> listOwnerNameRelsByMetalakeId(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listOwnerNameRelsByMetalakeId(metalakeId));
  }

  public List<SecurableObjectPO> listSecurableObjectsByRoleIds(Set<Long> roleIds) {
    if (roleIds.isEmpty()) {
      return Collections.emptyList();
    }
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listSecurableObjectsByRoleIds(roleIds));
  }

  public List<TagNameMetadataObjectRelPO> listTagNameMetadataObjectRelsByMetalakeId(
      long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class,
        mapper -> mapper.listTagNameMetadataObjectRelsByMetalakeId(metalakeId));
  }

  /**
   * Lists metadata object IDs with at least one current, enabled policy relation.
   *
   * @param metalakeId metalake ID
   * @return metadata object IDs covered directly by enabled policies
   */
  public Set<Long> listEnabledPolicyMetadataObjectIdsByMetalakeId(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class,
        mapper -> mapper.listEnabledPolicyMetadataObjectIdsByMetalakeId(metalakeId));
  }

  private void replaceMetrics(
      long metalakeId,
      Map<Long, List<MetricPO>> metricsByUser,
      long timestamp,
      boolean appendHistory,
      @Nullable Long dirtyEventTime) {
    List<MetricPO> metrics = flattenMetrics(metalakeId, metricsByUser, timestamp);
    SessionUtils.doWithCommit(
        MetricDataMapper.class,
        mapper -> {
          mapper.deleteCurrentMetrics(metalakeId);
          if (!metrics.isEmpty()) {
            insertMetricsInBatches(mapper, metrics, false);
            if (appendHistory) {
              insertMetricsInBatches(mapper, metrics, true);
            }
          }
          if (dirtyEventTime != null) {
            mapper.markMetalakeDirty(metalakeId, new Timestamp(dirtyEventTime));
          }
        });
  }

  private static List<MetricPO> mergeMetrics(
      List<MetricPO> historyMetrics, List<MetricPO> currentMetrics) {
    Map<String, MetricPO> metricByNameAndTimestamp = new LinkedHashMap<>();
    historyMetrics.forEach(metric -> metricByNameAndTimestamp.put(metricKey(metric), metric));
    // Current is added last so it wins when a daily history point has the same timestamp.
    currentMetrics.forEach(metric -> metricByNameAndTimestamp.put(metricKey(metric), metric));

    List<MetricPO> result = new ArrayList<>(metricByNameAndTimestamp.values());
    result.sort(
        Comparator.comparing(MetricPO::getMetricName).thenComparing(MetricPO::getCreatedTime));
    return result;
  }

  private static String metricKey(MetricPO metric) {
    return metric.getMetricName() + '\u0000' + metric.getCreatedTime().getTime();
  }

  private static List<MetricPO> flattenMetrics(
      long metalakeId, Map<Long, List<MetricPO>> metricsByUser, long timestamp) {
    Timestamp sharedTimestamp = new Timestamp(timestamp);
    List<MetricPO> result = new ArrayList<>();
    metricsByUser.forEach(
        (userId, metrics) ->
            metrics.forEach(
                metric ->
                    result.add(
                        MetricPO.builder()
                            .withMetalakeId(metalakeId)
                            .withUserId(userId)
                            .withMetricName(metric.getMetricName())
                            .withMetricValue(metric.getMetricValue())
                            .withMetricState(metric.getMetricState())
                            .withMetricMessage(metric.getMetricMessage())
                            .withCreatedTime(sharedTimestamp)
                            .build())));
    return result;
  }

  private static void insertMetricsInBatches(
      MetricDataMapper mapper, List<MetricPO> metrics, boolean history) {
    for (int start = 0; start < metrics.size(); start += INSERT_BATCH_SIZE) {
      List<MetricPO> batch =
          metrics.subList(start, Math.min(start + INSERT_BATCH_SIZE, metrics.size()));
      if (history) {
        mapper.insertMetricsDataBatch(batch);
      } else {
        mapper.insertCurrentMetrics(batch);
      }
    }
  }
}
