/*
 * Copyright 2024 Datastrato Pvt Ltd.
 * This software is licensed under the Apache License version 2.
 */
package com.datastrato.gravitino.metrics.storage.relational.service;

import com.datastrato.gravitino.metrics.MetricsCollector;
import com.datastrato.gravitino.metrics.dto.MetricDTO;
import com.datastrato.gravitino.metrics.storage.relational.MetricPO;
import com.datastrato.gravitino.metrics.storage.relational.OwnerNameRelPO;
import com.datastrato.gravitino.metrics.storage.relational.TagNameMetadataObjectRelPO;
import com.datastrato.gravitino.metrics.storage.relational.mapper.MetricDataMapper;
import com.datastrato.gravitino.metrics.storage.relational.utils.DatastratoPOConverters;
import java.sql.Timestamp;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import org.apache.gravitino.Entity;
import org.apache.gravitino.NameIdentifier;
import org.apache.gravitino.exceptions.NoSuchEntityException;
import org.apache.gravitino.exceptions.NoSuchMetalakeException;
import org.apache.gravitino.exceptions.NoSuchUserException;
import org.apache.gravitino.meta.UserEntity;
import org.apache.gravitino.server.authorization.MetadataAuthzHelper;
import org.apache.gravitino.storage.relational.po.SecurableObjectPO;
import org.apache.gravitino.storage.relational.po.UserRoleRelPO;
import org.apache.gravitino.storage.relational.service.MetalakeMetaService;
import org.apache.gravitino.storage.relational.service.UserMetaService;
import org.apache.gravitino.storage.relational.utils.SessionUtils;
import org.apache.gravitino.utils.NameIdentifierUtil;

public class MetricDataService {

  public static MetricDataService getInstance() {
    return INSTANCE;
  }

  private static final MetricDataService INSTANCE = new MetricDataService();

  private boolean enableAuthorization;

  @SuppressWarnings("unused")
  private MetricsCollector metricsCollector;

  private MetricDataService() {}

  public void initialize(boolean enableAuthorization) {
    this.enableAuthorization = enableAuthorization;
    this.metricsCollector = MetricsCollector.getInstance();
  }

  // For testing only
  void setMetricsCollector(MetricsCollector metricsCollector) {
    this.metricsCollector = metricsCollector;
  }

  public enum Metric {
    ASSET_COUNT("asset_count"),
    TAG_COUNT("tag_count"),
    CATALOG_COUNT("catalog_count"),
    SCHEMA_COUNT("schema_count"),
    TABLE_COUNT("table_count"),
    FILESET_COUNT("fileset_count"),
    TOPIC_COUNT("topic_count"),
    MODEL_COUNT("model_count"),
    TAGGED_ASSET_COUNT("tagged_asset_count"),
    UNTAGGED_ASSET_COUNT("untagged_asset_count"),
    PII_TAGGED_ASSET_COUNT("pii_tagged_asset_count"),
    PUBLIC_TAGGED_ASSET_COUNT("public_tagged_asset_count"),
    CONFIDENTIAL_TAGGED_ASSET_COUNT("confidential_tagged_asset_count"),
    PRIVATE_TAGGED_ASSET_COUNT("private_tagged_asset_count"),
    OWNED_ASSET_COUNT("owned_asset_count");

    private final String name;

    Metric(String name) {
      this.name = name;
    }

    public String getName() {
      return name;
    }

    public static Metric fromName(String name) {
      for (Metric metric : values()) {
        if (metric.name.equalsIgnoreCase(name)) {
          return metric;
        }
      }
      throw new IllegalArgumentException("Unknown metric name: " + name);
    }
  }

  public MetricDTO[] getMetricsByNameAndTimestamp(
      String metalakeName,
      String userName,
      String[] metricNames,
      long startTimestamp,
      long endTimestamp) {
    // this method is used by GravitinoMetricsService to query metrics, so we can not use
    // metalakeSnapshot, because it's generated by GravitinoMetricsService
    long metalakeId;
    try {
      metalakeId = MetalakeMetaService.getInstance().getMetalakeIdByName(metalakeName);
    } catch (NoSuchEntityException e) {
      throw new NoSuchMetalakeException(e, "Metalake not found: %s", metalakeName);
    }

    long userId = MetricsCollector.MOCK_USER_ID_FOR_DISABLE_AUTHZ;
    if (enableAuthorization) {
      try {
        UserEntity userEntity =
            UserMetaService.getInstance()
                .getUserByIdentifier(NameIdentifierUtil.ofUser(metalakeName, userName));
        userId = userEntity.id();
      } catch (NoSuchEntityException e) {
        throw new NoSuchUserException(
            e, "User not found: %s for metalake: %s", userName, metalakeName);
      }
      NameIdentifier[] authResult =
          MetadataAuthzHelper.filterByExpression(
              metalakeName,
              "METALAKE::OWNER",
              Entity.EntityType.METALAKE,
              new NameIdentifier[] {NameIdentifierUtil.ofMetalake(metalakeName)});
      userId = authResult.length == 0 ? userId : MetricsCollector.MOCK_USER_ID_FOR_METALAKE_OWNER;
    }

    long finalUserId = userId;
    List<MetricPO> metricPOs =
        SessionUtils.getWithoutCommit(
            MetricDataMapper.class,
            mapper ->
                mapper.getMetricPOsByUserIdMetricNamesAndTimestamp(
                    metalakeId,
                    finalUserId,
                    metricNames,
                    new Timestamp(startTimestamp),
                    new Timestamp(endTimestamp)));
    return DatastratoPOConverters.fromMetricPOs(metricPOs);
  }

  public long getTagCountByMetalakeId(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.getTagCountByMetalakeId(metalakeId));
  }

  public void insertMetrics(long metalakeId, long userId, List<MetricPO> metrics) {
    if (metrics.isEmpty()) {
      return;
    }
    SessionUtils.doWithCommit(
        MetricDataMapper.class, mapper -> mapper.insertMetricsData(metalakeId, userId, metrics));
  }

  public void cleanMetricsByTimestamp(long oldestTimestamp) {
    SessionUtils.doWithCommit(
        MetricDataMapper.class,
        mapper -> mapper.cleanMetricsByTimestamp(new Timestamp(oldestTimestamp)));
  }

  public void cleanInvalidMetrics() {
    SessionUtils.doWithCommit(MetricDataMapper.class, MetricDataMapper::cleanInvalidMetrics);
  }

  public List<UserRoleRelPO> listUserRoleRelsByUserIds(Set<Long> userIds) {
    if (userIds.isEmpty()) {
      return Collections.emptyList();
    }
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listUserRoleRelsByUserIds(userIds));
  }

  public List<OwnerNameRelPO> listOwnerNameRelsByMetalakeId(long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listOwnerNameRelsByMetalakeId(metalakeId));
  }

  public List<SecurableObjectPO> listSecurableObjectsByRoleIds(Set<Long> roleIds) {
    if (roleIds.isEmpty()) {
      return Collections.emptyList();
    }
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class, mapper -> mapper.listSecurableObjectsByRoleIds(roleIds));
  }

  public List<TagNameMetadataObjectRelPO> listTagNameMetadataObjectRelsByMetalakeId(
      long metalakeId) {
    return SessionUtils.getWithoutCommit(
        MetricDataMapper.class,
        mapper -> mapper.listTagNameMetadataObjectRelsByMetalakeId(metalakeId));
  }
}
