--
-- Copyright 2023 Datastrato Pvt Ltd.
-- This software is licensed under the Apache License version 2.
--

CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    metric_name VARCHAR(64) NOT NULL,
    metric_value double precision NOT NULL DEFAULT 0.0,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_mi_ui_ct ON dashboard_metrics (metalake_id, user_id, created_time);
CREATE INDEX IF NOT EXISTS idx_ct_da ON dashboard_metrics (created_time);

COMMENT ON TABLE dashboard_metrics IS 'dashboard metrics';
COMMENT ON COLUMN dashboard_metrics.id IS 'auto increment id';
COMMENT ON COLUMN dashboard_metrics.metalake_id IS 'metalake id';
COMMENT ON COLUMN dashboard_metrics.user_id IS 'user id who owns this metric';
COMMENT ON COLUMN dashboard_metrics.metric_name IS 'metric name, such as catalogCount, schemaCount, etc.';
COMMENT ON COLUMN dashboard_metrics.metric_value IS 'metric value';
COMMENT ON COLUMN dashboard_metrics.created_time IS 'metric created time';