--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file--
--  distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"). You may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- using default 'unknown' to fill in the new column for compatibility
ALTER TABLE fileset_version_info ADD COLUMN storage_location_name VARCHAR(256) NOT NULL DEFAULT 'unknown';
COMMENT ON COLUMN fileset_version_info.storage_location_name IS 'fileset storage location name';
ALTER TABLE fileset_version_info DROP CONSTRAINT fileset_version_info_fileset_id_version_deleted_at_key;
ALTER TABLE fileset_version_info ADD CONSTRAINT uk_fid_ver_sto_del UNIQUE (fileset_id, version, storage_location_name, deleted_at);
-- remove the default value for storage_location_name
ALTER TABLE fileset_version_info ALTER COLUMN storage_location_name DROP DEFAULT;
-- Enterprise-specific table
CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    metric_name VARCHAR(64) NOT NULL,
    metric_value double precision NOT NULL DEFAULT 0.0,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_mi_ui_ct ON dashboard_metrics (metalake_id, user_id, created_time);
CREATE INDEX IF NOT EXISTS idx_ct_da ON dashboard_metrics (created_time);

COMMENT ON TABLE dashboard_metrics IS 'dashboard metrics';
COMMENT ON COLUMN dashboard_metrics.id IS 'auto increment id';
COMMENT ON COLUMN dashboard_metrics.metalake_id IS 'metalake id';
COMMENT ON COLUMN dashboard_metrics.user_id IS 'user id who owns this metric';
COMMENT ON COLUMN dashboard_metrics.metric_name IS 'metric name, such as catalogCount, schemaCount, etc.';
COMMENT ON COLUMN dashboard_metrics.metric_value IS 'metric value';
COMMENT ON COLUMN dashboard_metrics.created_time IS 'metric created time';
