#
# Copyright 2023 Datastrato Pvt Ltd.
# This software is licensed under the Apache License version 2.
#
# jdbc-url = jdbc:oracle:thin:@localhost:1521:ORCL
# jdbc-user = gravitino
# jdbc-password = gravitino
# jdbc-driver = oracle.jdbc.OracleDriver
