name: Backend Integration Test

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Integration test for AMD64 architecture
  test-amd64-arch:
    if: github.event.label.name == 'run-ci'
    runs-on: [self-hosted, linux, x64, amazon, xlarge]
    timeout-minutes: 120
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
        test-mode: [ deploy ]
        backend: [ mysql ]
    env:
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check required command
        run: |
          gravitino-oss/dev/ci/check_commands.sh

      - name: Package Gravitino
        if : ${{ matrix.test-mode == 'deploy' }}
        run: |
          ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

      - name: Free up disk space
        run: |
          gravitino-oss/dev/ci/util_free_space.sh

      - name: Copy distribution package
        run: |
          cp -r -f ./distribution ./gravitino-oss

      - name: Run Backend Integration Test
        id: integrationTest
        run: >
          ./gradlew -p gravitino-oss test -PskipTests -PtestMode=${{ matrix.test-mode }} -PjdkVersion=${{ matrix.java-version }} -PjdbcBackend=${{ matrix.backend }} -PskipDockerTests=false
          -x :web:web:test -x :web:integration-test:test -x :clients:client-python:test -x :flink-connector:flink:test -x :spark-connector:spark-common:test 
          -x :spark-connector:spark-3.3:test -x :spark-connector:spark-3.4:test -x :spark-connector:spark-3.5:test 
          -x :spark-connector:spark-runtime-3.3:test -x :spark-connector:spark-runtime-3.4:test -x :spark-connector:spark-runtime-3.5:test
          -x :authorizations:authorization-ranger:test -x :trino-connector:integration-test:test -x :trino-connector:trino-connector:test
          -x :catalogs:catalog-jdbc-oceanbase:test

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: integrate-test-reports-${{ matrix.java-version }}-${{ matrix.test-mode }}-${{ matrix.backend }}
          path: |
            gravitino-oss/build/reports
            gravitino-oss/iceberg/iceberg-rest-server/build/*.log
            gravitino-oss/integration-test/build/*.log
            gravitino-oss/integration-test/build/*.tar
            gravitino-oss/integration-test/build/trino-ci-container-log/hive/*.*
            gravitino-oss/integration-test/build/trino-ci-container-log/hdfs/*.*
            gravitino-oss/distribution/package/logs/*.out
            gravitino-oss/distribution/package/logs/*.log
            gravitino-oss/catalogs/**/*.log
            gravitino-oss/catalogs/**/*.tar
            gravitino-oss/distribution/**/*.log

