name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64, ubuntu-latest]
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    strategy:
      matrix:
        # The enterprise edition only needs to test one Java version,
        # and because Trino requires at least Java 17, we choose Java 17 for testing.
        java-version: [ 17 ]
    timeout-minutes: 60
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload unit tests report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit test report
          path: |
            build/reports
            catalogs/**/*.log
            catalogs/**/*.tar
            search/build/reports

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: 'Code Coverage Report'
          debug-mode: false
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
