name: Cloud Test

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Integration test for AMD64 architecture
  test-amd64-arch:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: gcp-arc-runners
    env:
      GRAVITINO_TEST_CLOUD_IT: true
      S3_STS_ACCESS_KEY_ID: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_STS_SECRET_ACCESS_KEY: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      S3_STS_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_STS_BUCKET_NAME: ${{ vars.S3_BUCKET }}
      S3_STS_REGION: ${{ vars.S3_REGION }}
      S3_STS_ROLE_ARN: ${{ vars.S3_ROLE_ARN }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      S3_BUCKET_NAME: ${{ vars.S3_BUCKET }}
      PLATFORM: ${{ matrix.architecture }}
      S3_ACCESS_KEY_ID_FOR_CREDENTIAL: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      S3_BUCKET_NAME_FOR_CREDENTIAL: ${{ vars.S3_BUCKET }}
      S3_ENDPOINT_FOR_CREDENTIAL: ${{ vars.S3_ENDPOINT }}
      S3_REGION_FOR_CREDENTIAL: ${{ vars.S3_REGION }}
      S3_ROLE_ARN_FOR_CREDENTIAL: ${{ vars.S3_ROLE_ARN }}
      S3_ROLE_ARN: ${{ vars.S3_ROLE_ARN }}
      S3_SECRET_ACCESS_KEY_FOR_CREDENTIAL: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      GCS_BUCKET_NAME_FOR_CREDENTIAL: ${{ vars.GCS_BUCKET }}
      GCS_SERVICE_ACCOUNT_JSON_PATH_FOR_CREDENTIAL: ${{ vars.GCS_SERVICE_ACCOUNT_JSON_PATH }}
      GCS_BUCKET_NAME: ${{ vars.GCS_BUCKET }}
      GCS_SERVICE_ACCOUNT_JSON_PATH: ${{ vars.GCS_SERVICE_ACCOUNT_JSON_PATH }}
      GCS_SERVICE_ACCOUNT_JSON_CONTENT: ${{ secrets.GCS_SERVICE_ACCOUNT_JSON_CONTENT }}
      GRAVITINO_HOME: ${{ github.workspace }}/distribution/package
      PYTHON_BUILD_PATH: ${{ github.workspace }}/clients/client-python/build
      GRAVITINO_CI_HIVE_DOCKER_IMAGE: apache/gravitino-ci:hive-0.1.20
      DOCKER_TEST: "true"
      GRAVITINO_GCS_BUCKET: ${{ vars.GCS_BUCKET }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GCS_SERVICE_ACCOUNT_JSON_PATH }}
      GRAVITINO_S3_ACCESS_KEY: ${{ secrets.S3_STS_ACCESS_KEY_ID }}
      GRAVITINO_S3_BUCKET: ${{ vars.S3_BUCKET }}
      GRAVITINO_S3_REGION: ${{ vars.S3_REGION }}
      GRAVITINO_S3_ROLE_ARN: ${{ vars.S3_ROLE_ARN }}
      GRAVITINO_S3_SECRET_KEY: ${{ secrets.S3_STS_SECRET_ACCESS_KEY }}
      LICENSE_PUBLIC_KEY_URL: ${{ secrets.ENTERPRISE_TEST_PUBLIC_KEY_URI }}
      GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      GRAVITINO_LICENSE_KEY: ${{ secrets.ENTERPRISE_TEST_LICENSE_KEY }}
    timeout-minutes: 90
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
        test-mode: [ deploy ]
        backend: [ mysql ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            gradle/libs.versions.toml
            gradle.properties

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Check required command
        run: |
          echo "$GCS_SERVICE_ACCOUNT_JSON_CONTENT" > ${{ vars.GCS_SERVICE_ACCOUNT_JSON_PATH }}
          dev/ci/check_commands.sh
          cat ${{ vars.GCS_SERVICE_ACCOUNT_JSON_PATH }}

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package
        run: |
          export MINIFORGE_BIN="$GITHUB_WORKSPACE/.gradle/python/Linux/Miniforge3/bin"
          export PATH="$MINIFORGE_BIN:$PATH"
          
          ./gradlew build -x checkNewFileLicenseHeaders -x test
          mkdir -p /tmp/bundles
          cp -r bundles/*-bundle/build/libs/*.jar /tmp/bundles

          mkdir -p /tmp/irc-bundles
          cp -r bundles/iceberg-*/build/libs/*.jar /tmp/irc-bundles
          ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

          # distribution already at repo root after flat build
          cp -r /tmp/bundles/* ./distribution/package/catalogs/fileset/libs
          cp -r /tmp/irc-bundles/* ./distribution/package/iceberg-rest-server/libs

      - name: IRC IcebergRESTS3TokenIT Test
        run: |
          ./gradlew -PskipTests -PtestMode=${{ matrix.test-mode }} -PskipDockerTests=false :iceberg:iceberg-rest-server:test --tests "org.apache.gravitino.iceberg.integration.test.IcebergRESTS3TokenIT"

      - name: IRC IcebergRESTGCSIT Test
        run: |
          ./gradlew -PskipTests -PtestMode=${{ matrix.test-mode }} -PskipDockerTests=false :iceberg:iceberg-rest-server:test --tests "org.apache.gravitino.iceberg.integration.test.IcebergRESTGCSIT"

      - name: Fileset Cloud Integration Test python
        id: integrationTest1
        run: |
          echo "==============start gravitino server================="
          cd distribution/package/bin
          pwd
          ./gravitino.sh start
          cd -
          pwd
          cd clients/client-python
          python3 -m venv venv
          source venv/bin/activate
          pip install .
          pip install -r requirements-dev.txt
          echo "============ Start to run test_gvfs_with_s3 and test_gvfs_with_s3_credential ============"
          python -m unittest tests.integration.test_gvfs_with_s3_credential -v
          echo "============ Start to run test_gvfs_with_gcs and test_gvfs_with_gcs_credential ============"
          python -m unittest tests.integration.test_gvfs_with_gcs_credential -v
          echo "==============stop gravitino server================="
          cd -
          cd distribution/package/bin
          ./gravitino.sh stop
      - name: Update S3_BUCKET_NAME env var
        run: |
          echo "S3_BUCKET_NAME=amzn-s3-ci-sydney-bucket" >> "$GITHUB_ENV"

      - name: Fileset Cloud Integration Test java
        run: |
          ./gradlew -PskipTests -PtestMode=${{ matrix.test-mode }} -PjdkVersion=${{ matrix.java-version }} -PjdbcBackend=${{ matrix.backend }} -PskipDockerTests=false :clients:filesystem-hadoop3:test --tests "org.apache.gravitino.filesystem.hadoop.integration.test.**"

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: integrate test reports-${{ matrix.java-version }}-${{ matrix.test-mode }}-${{ matrix.backend }}
          path: |
            build/reports
            iceberg/iceberg-rest-server/build/*.log
            integration-test/build/*.log
            integration-test/build/*.tar
            integration-test/build/trino-ci-container-log/hive/*.*
            integration-test/build/trino-ci-container-log/hdfs/*.*
            catalogs/**/*.log
            catalogs/**/*.tar
            distribution/**/*.log
            distribution/**/*.out
