name: Search Integration Test

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            source_changes:
              - .github/**
              - api/**
              - authorization-jdbc-enterprise/**
              - bin/**
              - common/**
              - common-extension/**
              - conf/**
              - core/**
              - core-extension/**
              - datastrato-server/**
              - dev/**
              - gradle/**
              - iceberg/**
              - integration-test-common/**
              - lance/**
              - scripts/**
              - search/**
              - server/**
              - server-common/**
              - test/**
              - build.gradle.kts
              - gradle.properties
              - gradlew
              - settings.gradle.kts
    outputs:
      source_changes: ${{ steps.filter.outputs.source_changes }}

  # Integration test for AMD64 architecture
  test-amd64-arch:
    needs: changes
    if: needs.changes.outputs.source_changes == 'true'
    runs-on: [self-hosted, linux, x64, ubuntu-latest, 2xlarge]
    timeout-minutes: 120
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
        test-mode: [ deploy ]
    env:
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check required command
        run: |
          dev/ci/check_commands.sh

      - name: Package Gravitino
        if : ${{ matrix.test-mode == 'deploy' }}
        run: |
           ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

      - name: Free up disk space
        run: |
          dev/ci/util_free_space.sh

      - name: Run Search Integration Test
        id: integrationTest
        run: >
          ./gradlew :test:search-integration-test:test  -PskipTests -PtestMode=deploy -PjdkVersion=17 -PskipDockerTests=false

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: integrate-test-reports-${{ matrix.java-version }}-${{ matrix.test-mode }}-${{ matrix.backend }}
          path: |
            build/reports
            iceberg/iceberg-rest-server/build/*.log
            integration-test/build/*.log
            integration-test/build/*.tar
            integration-test/build/trino-ci-container-log/hive/*.*
            integration-test/build/trino-ci-container-log/hdfs/*.*
            distribution/package/logs/*.out
            distribution/package/logs/*.log
            catalogs/**/*.log
            catalogs/**/*.tar
            distribution/**/*.log
            test/search-integration-test/build/reports
            distribution/package/logs/*.out
            distribution/package/logs/*.log

