name: Search Integration Test

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Integration test for AMD64 architecture
  test-amd64-arch:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: [self-hosted, linux, x64, ubuntu-latest, 2xlarge]
    timeout-minutes: 120
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
        test-mode: [ deploy ]
    env:
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check required command
        run: |
          gravitino-internal/dev/ci/check_commands.sh

      - name: Package Gravitino
        if : ${{ matrix.test-mode == 'deploy' }}
        run: |
           ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

      - name: Free up disk space
        run: |
          gravitino-internal/dev/ci/util_free_space.sh

      - name: Run Search Integration Test
        id: integrationTest
        run: >
          ./gradlew :test:search-integration-test:test  -PskipTests -PtestMode=deploy -PjdkVersion=17 -PskipDockerTests=false

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: integrate-test-reports-${{ matrix.java-version }}-${{ matrix.test-mode }}-${{ matrix.backend }}
          path: |
            gravitino-internal/build/reports
            gravitino-internal/iceberg/iceberg-rest-server/build/*.log
            gravitino-internal/integration-test/build/*.log
            gravitino-internal/integration-test/build/*.tar
            gravitino-internal/integration-test/build/trino-ci-container-log/hive/*.*
            gravitino-internal/integration-test/build/trino-ci-container-log/hdfs/*.*
            gravitino-internal/distribution/package/logs/*.out
            gravitino-internal/distribution/package/logs/*.log
            gravitino-internal/catalogs/**/*.log
            gravitino-internal/catalogs/**/*.tar
            gravitino-internal/distribution/**/*.log
            test/search-integration-test/build/reports
            distribution/package/logs/*.out
            distribution/package/logs/*.log

