name: Spark Integration Test

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: [ "main", "branch-*", "internal-*", "oss-main" ]
  pull_request:
    types: [labeled]
    branches: [ "main", "branch-*", "internal-*", "oss-main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          filters: |
            source_changes:
              - .github/**
              - api/**
              - authorization-jdbc-enterprise/**
              - bin/**
              - bundles/**
              - catalogs/**
              - clients/client-java/**
              - clients/client-java-runtime/**
              - common/**
              - common-extension/**
              - conf/**
              - core/**
              - core-extension/**
              - datastrato-server/**
              - dev/**
              - gradle/**
              - iceberg/**
              - integration-test-common/**
              - scripts/**
              - server/**
              - server-common/**
              - spark-connector/**
              - build.gradle.kts
              - gradle.properties
              - gradlew
              - settings.gradle.kts
    outputs:
      source_changes: ${{ steps.filter.outputs.source_changes }}

  SparkIT-on-push:
    needs: changes
    if: (github.event_name == 'push' && needs.changes.outputs.source_changes == 'true')
    strategy:
      matrix:
        # Integration test for ARM64 architecture
        architecture: [ linux/arm64 ]
        java-version: [ 17 ]
        scala-version: [ 2.12 ]
        test-mode: [ deploy ]
    uses: ./.github/workflows/spark-integration-test-action.yml
    with:
      architecture: ${{ matrix.architecture }}
      java-version: ${{ matrix.java-version }}
      scala-version: ${{ matrix.scala-version }}
      test-mode: ${{ matrix.test-mode }}
    secrets: inherit

  SparkIT-on-pr:
    needs: changes
    if: (github.event_name == 'pull_request' && needs.changes.outputs.source_changes == 'true')
    strategy:
      matrix:
        # Integration test for ARM64 architecture
        architecture: [ linux/arm64 ]
        java-version: [ 17 ]
        scala-version: [ 2.12 ]
        test-mode: [ deploy ]
    uses: ./.github/workflows/spark-integration-test-action.yml
    with:
      architecture: ${{ matrix.architecture }}
      java-version: ${{ matrix.java-version }}
      scala-version: ${{ matrix.scala-version }}
      test-mode: ${{ matrix.test-mode }}
    secrets: inherit
